name: Node Continuous Integration

on:
  pull_request:
    branches: [ master ] 
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test
      - run: npm run build
      - uses: actions/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Enable linters
          eslint: true
     # - run: npm install eslint --save-dev
      #- run: npx eslint .
      # - run: npx eslint . --fix
      
 


